// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class LayoutsController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string One = "One";
                public readonly string Two = "Two";
            }
            public readonly string One = "~/Views/Layouts/One.cshtml";
            public readonly string Two = "~/Views/Layouts/Two.cshtml";
            static readonly _ComponentsClass s_Components = new _ComponentsClass();
            public _ComponentsClass Components { get { return s_Components; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ComponentsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Breadcrumbs = "Breadcrumbs";
                    public readonly string Footer = "Footer";
                    public readonly string LeftMenu = "LeftMenu";
                    public readonly string Scripts = "Scripts";
                    public readonly string Tabs = "Tabs";
                }
                public readonly string Breadcrumbs = "~/Views/Layouts/Components/Breadcrumbs.cshtml";
                public readonly string Footer = "~/Views/Layouts/Components/Footer.cshtml";
                public readonly string LeftMenu = "~/Views/Layouts/Components/LeftMenu.cshtml";
                public readonly string Scripts = "~/Views/Layouts/Components/Scripts.cshtml";
                public readonly string Tabs = "~/Views/Layouts/Components/Tabs.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
